### ISSUE TITLE
About KVS_WebRTC_on_AmebaPro 

### ISSUE THREAD

**Issue by xiaoxiaoLily** [HungTseLee/KVS_WebRTC_on_AmebaPro#3]
Hi， HungTseLee
我在GitHub上下载的KVS_WebRTC_on_AmebaPro代码，根据文档指导配置了之后，在RTL8715A的官方开发板上烧录运行，sensor板型号为GC2053，运行起来之后，我从串口日志信息中看到程序一直卡在 get isp data这里一直循环，烦请帮忙指导下这个问题该如何解决，万分感谢！

**Comment by HungTseLee** [comment]
Hi @xiaoxiaoLily 
請問是使用哪一個example?
是否在/project/realtek_amebapro_v0_example/inc/sensor.h中有#define SENSOR_USE      	SENSOR_GC2053

**Comment by xiaoxiaoLily** [comment]
Hi， HungTseLee
我打开的是\KVS_WebRTC_on_AmebaPro\project\realtek_amebapro_v0_example的工程，platform_opts.h的配置如下：
/* For KVS Producer example*/ 
#define CONFIG_EXAMPLE_KVS_PRODUCER             1
在/project/realtek_amebapro_v0_example/inc/sensor.h中有 #define SENSOR_USE SENSOR_GC2053，并在\component\soc\realtek\8195b\misc\bsp\image下重命名isp_sc2232.bin为isp.bin，再编译烧录到开发板的。

**Comment by HungTseLee** [comment]
Hi @xiaoxiaoLily 

"并在\component\soc\realtek\8195b\misc\bsp\image下重命名isp_sc2232.bin为isp.bin" -->這個步驟不用做試試看

**Comment by xiaoxiaoLily** [comment]
Hi， HungTseLee
"并在\component\soc\realtek\8195b\misc\bsp\image下重命名isp_sc2232.bin为isp.bin" -->這個步驟不用做試試看
按照如上指示重新编译烧录之后，程序运行的结果还是一样的，有如下打印信息：
... ...
Interface 0 IP address : 192.168.1.103
WIFI initialized

init_thread(56), Available heap 0x1d96e60wifi connected
waiting get epoch timer
waiting get epoch timer
[H264] init video related settings
start isp_cmd_thread
VOE OFF
isp addr = 98040220
[H264] create encoder
[H264] get & set encoder parameters

h264_set_parmeter err 720, 1280
[H264] init encoder
[ISP] init ISP
stream id = 0 0
Start recording
xQueueReceive
xQueueReceive
xQueueReceive
... ...
程序运行到[ISP] get isp data会卡在xQueueReceive()这个函数这里一直循环。

**Comment by HungTseLee** [comment]
h264_set_parmeter err 720, 1280
-->有設置h264參數嗎 看起來有設定錯誤

**Comment by xiaoxiaoLily** [comment]
Hi， HungTseLee
我并没有设置h264参数。
程序运行到\KVS_WebRTC_on_AmebaPro\component\common\example\kvs_producer\kvs_producer.c文件里的第287行就是这个打印：h264_set_parmeter err 720, 1280，但是从代码来看，这个打印并不是参数设定错误而打印的，你可以对照这个位置看下，我检查过的，所以应该不是这个原因呢。

**Comment by HungTseLee** [comment]
Hi @xiaoxiaoLily 
請問是參考這份文件嗎: https://github.com/HungTseLee/KVS_WebRTC_on_AmebaPro/blob/main/AmebaPro_Amazon_KVS_Producer_Getting_Started_Guide_v1.2.pdf

這份文件是KVS producer的使用說明

**Comment by HungTseLee** [comment]
We will close the issue. Please let us know in case of any further questions and feel free to reopen it or create a new one.

**Comment by xiaoxiaoLily** [comment]
Hi， HungTseLee
很抱歉，前段时间因为忙于其他项目，这个事情暂时搁置了，我按照文档的指导设置并编译好固件烧录到开发板，运行的结果跟之前反馈的现象还是一样的，打印如下：
init_thread(56), Available heap 0x1d98640
== Rtl8195bh IoT Platform ==
Chip VID: 0, Ver: 2
ROM Version: v3.0
Bus_IDAU 7: 0x20109940 ~ 0x20126698 as Non-Secure
tsi 701fb060

== RAM Start 1 ==
Build @ 11:03:10, Dec 30 2021

$8195bh>isp log service start
interface 0 is initialized
interface 1 is initialized

Initializing WIFI ...
RTL871X: [HALMAC]11692M
HALMAC_MAJOR_VER = 1
HALMAC_PROTOTYPE_VER = 4
HALMAC_MINOR_VER = 14
HALMAC_PATCH_VER = 0

RTL871X: efuse autoload en: 1

RTL871X: rfe_type=0x0, map=0x0

RTL871X: Download fw addr:9819a180, size:115560
- download_firmware_88xx HALMAC_RET_SUCCESS

RTL871X: fw: 24.4

RTL871X: RFE type = 0x0

RTL871X: 5g_tx_tank: 0xea, enable: 1

Start LOG SERVICE MODE

# start_addr=(0x4000), end_addr=(0x8000), buffer_size=(0x4000), smp_number_max=(2048)
ort fast connection

WIFI initialized

init_thread(56), Available heap 0x1d98640
#
#ATW0=360WiFi-0AA719
[ATW0]: _AT_WLAN_SET_SSID_ [360WiFi-0AA719]

[MEM] After do cmd, available heap 31038176


# ATW1=150531wei
[ATW1]: _AT_WLAN_SET_PASSPHRASE_ [150531wei]

[MEM] After do cmd, available heap 31038176


# 
#ATWC
[ATWC]: _AT_WLAN_JOIN_NET_

Joining BSS by SSID 360WiFi-0AA719...

[Driver]: set ssid [360WiFi-0AA719] 

[Driver]: start auth to 5c:27:d4:0a:a7:19

[Driver]: auth success, start assoc

[Driver]: association success(res=1)
rtw_hal_set_fw_rsvd_page PageSize: 128, RsvdPageNUm: 24

RTL871X: wlan0: DL RSVD page success! DLBcnCount:1, poll:1

[Driver]: set pairwise key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4)

[Driver]: set group key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4) keyid:1

Connected after 4292ms.


 wlan_wrtie_reconnect_data_to_flash():not the same ssid/passphrase/channel/offer_ip, write new profile to flash
Interface 0 IP address : 192.168.0.10

Got IP after 6312ms.


[MEM] After do cmd, available heap 31032064


# wifi connected
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
waiting get epoch timer
[H264] init video related settings
start isp_cmd_thread
VOE OFF
isp addr = 98040220
[H264] create encoder
[H264] get & set encoder parameters

h264_set_parmeter err 720, 1280
[H264] init encoder
[ISP] init ISP
stream id = 0 0
Start recording
xQueueReceive
xQueueReceive
xQueueReceive
xQueueReceive
... ...
