### ISSUE TITLE
KVS_WebRTC_on_AmebaPro KVS Demo

### ISSUE THREAD

**Issue by xiaoxiaoLily** [HungTseLee/KVS_WebRTC_on_AmebaPro#5]
Hi， HungTseLee
很抱歉，前段时间因为忙于其他项目，这个事情暂时搁置了，我按照文档的指导设置并编译好固件烧录到开发板，运行的结果跟之前反馈的现象还是一样的，打印如下：
init_thread(56), Available heap 0x1d98640
== Rtl8195bh IoT Platform ==
Chip VID: 0, Ver: 2
ROM Version: v3.0
Bus_IDAU 7: 0x20109940 ~ 0x20126698 as Non-Secure
tsi 701fb060

== RAM Start 1 ==
Build @ 11:03:10, Dec 30 2021

$8195bh>isp log service start
interface 0 is initialized
interface 1 is initialized

Initializing WIFI ...
RTL871X: [HALMAC]11692M
HALMAC_MAJOR_VER = 1
HALMAC_PROTOTYPE_VER = 4
HALMAC_MINOR_VER = 14
HALMAC_PATCH_VER = 0

RTL871X: efuse autoload en: 1

RTL871X: rfe_type=0x0, map=0x0

RTL871X: Download fw addr:9819a180, size:115560
- download_firmware_88xx HALMAC_RET_SUCCESS

RTL871X: fw: 24.4

RTL871X: RFE type = 0x0

RTL871X: 5g_tx_tank: 0xea, enable: 1

Start LOG SERVICE MODE

# start_addr=(0x4000), end_addr=(0x8000), buffer_size=(0x4000), smp_number_max=(2048)
ort fast connection

WIFI initialized

init_thread(56), Available heap 0x1d98640
#
#ATW0=360WiFi-0AA719
[ATW0]: _AT_WLAN_SET_SSID_ [360WiFi-0AA719]

[MEM] After do cmd, available heap 31038176

# ATW1=150531wei
[ATW1]: _AT_WLAN_SET_PASSPHRASE_ [150531wei]

[MEM] After do cmd, available heap 31038176

# 
#ATWC
[ATWC]: _AT_WLAN_JOIN_NET_

Joining BSS by SSID 360WiFi-0AA719...

[Driver]: set ssid [360WiFi-0AA719] 

[Driver]: start auth to 5c:27:d4:0a:a7:19

[Driver]: auth success, start assoc

[Driver]: association success(res=1)
rtw_hal_set_fw_rsvd_page PageSize: 128, RsvdPageNUm: 24

RTL871X: wlan0: DL RSVD page success! DLBcnCount:1, poll:1

[Driver]: set pairwise key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4)

[Driver]: set group key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4) keyid:1

Connected after 4292ms.

 wlan_wrtie_reconnect_data_to_flash():not the same ssid/passphrase/channel/offer_ip, write new profile to flash
Interface 0 IP address : 192.168.0.10

Got IP after 6312ms.

[MEM] After do cmd, available heap 31032064

# wifi connected
waiting get epoch timer
waiting get epoch timer
... ...
[H264] init video related settings
start isp_cmd_thread
VOE OFF
isp addr = 98040220
[H264] create encoder
[H264] get & set encoder parameters

h264_set_parmeter err 720, 1280
[H264] init encoder
[ISP] init ISP
stream id = 0 0
Start recording
xQueueReceive
xQueueReceive
... ...

**Comment by HungTseLee** [comment]
收到 我這邊試試看，若可以的話再更新我的使用步驟給你

**Comment by xiaoxiaoLily** [comment]
Hi， HungTseLee
好的，你这边OK的话，烦请尽快指导下我哦，感谢感谢~

**Comment by HungTseLee** [comment]
Hi @xiaoxiaoLily 
我這邊按照您的配置 是沒有問題的(amebapro+GC2053)
這邊提供我的使用步驟讓您嘗試:
1. "git clone --recurse-submodules https://github.com/HungTseLee/KVS_WebRTC_on_AmebaPro.git"
2. 於project/realtek_amebapro_v0_example/inc/sensor.h中#define SENSOR_USE  SENSOR_GC2053
3. 於project/realtek_amebapro_v0_example/inc/platform_opts.h中#define CONFIG_EXAMPLE_KVS_PRODUCER_MMF  1
4. 於component/common/example/kvs_producer/sample_config.h中配置AWS_ACCESS_KEY與AWS_SECRET_KEY
5. 編譯KVS project: "make -f Makefile_amazon_kvs all"

**Comment by xiaoxiaoLily** [comment]
Hi， HungTseLee
感谢提供支持，你提供的步骤与我这边参考指导文档只有一点不同，即#define CONFIG_EXAMPLE_KVS_PRODUCER_MMF 1，我之前配置的是#define CONFIG_EXAMPLE_KVS_PRODUCER 1，按照你所述的步骤编译的固件烧录到开发板之后，没再出现我之前反馈的问题，现在的日志如下：
... ...
waiting get epoch timer
[Video resolution] w: 1920 h: 1080
Try to describe stream
PUT MEDIA endpoint: s-670061c1.kinesisvideo.ap-southeast-1.amazonaws.com
Try to put media
Info: 100-continue
Info: Invalid NALU format
Failed to convert Annex-B to AVCC
Error: Time:Wed Jan 12 13:15:57 2022
                                     File:netio.c Func:NetIo_Send Line:269 SSL send error -78
Error: Time:Wed Jan 12 13:15:57 2022
                                     File:restapi.c Func:Kvs_putMediaUpdate Line:945 Failed to send data frame
Failed to update
Leaving put media
PUT MEDIA endpoint: s-670061c1.kinesisvideo.ap-southeast-1.amazonaws.com
Try to put media
Info: 100-continue
Info: Invalid NALU format
Failed to convert Annex-B to AVCC
Error: Time:Wed Jan 12 13:35:10 2022
                                     File:netio.c Func:NetIo_Send Line:269 SSL send error -78
Error: Time:Wed Jan 12 13:35:10 2022
                                     File:restapi.c Func:Kvs_putMediaUpdate Line:945 Failed to send data frame
Failed to update
Leaving put media
PUT MEDIA endpoint: s-670061c1.kinesisvideo.ap-southeast-1.amazonaws.com
Try to put media
Info: 100-continue
Info: Invalid NALU format
Failed to convert Annex-B to AVCC
Info: Invalid NALU format
Failed to convert Annex-B to AVCC
Info: Invalid NALU format
Failed to convert Annex-B to AVCC
Info: Invalid NALU format
Failed to convert Annex-B to AVCC
... ...

从日志来看还是有问题，推流失败请再帮忙看看，谢谢~

**Comment by xiaoxiaoLily** [comment]
Hi， HungTseLee
你的意思是从日志信息来看，目前我遇到的问题是由于网络环境差引起的吗？目前我隔离在家，用的是家里的中国移动宽带网络。

**Comment by xiaoxiaoLily** [comment]
Hi， HungTseLee
KVS Demo在realtek平台上跑通了，现在可以在AWS上看到推的流数据了，非常感谢您的支持和指导，谢谢~

**Comment by HungTseLee** [comment]
Hi @xiaoxiaoLily 
好的，若有其他問題可以在讓我們了解~謝謝~
